

// const dishDict: Record<string, string> = {
//   "paneer pyaza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1753189879/Paneer-Do-Pyaza-2-3_konl7d.jpg",
//   "paneer makhni": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1753189817/paneer-butter-masala-recipe_yeumfs.webp",
//   "Paneer Tikka": "",
//   "Hara Bhara Kabab": "",
//   "Veg Cutlet": "",
//   "Spring Roll": "",
//   "Stuffed Mushrooms": "",
//   "Chicken Tikka": "",
//   "Malai Tikka": "",
//   "Fish Tikka": "",
//   "Mutton Seekh Kebab": "",
//   "Chilli Paneer Dry": "",
//   "Chilli Chicken": "",
//   "Gobi Manchurian": "",
//   "Nachos with Cheese": "",
//   "Tomato Soup": "",
//   "Sweet Corn Soup": "",
//   "Hot & Sour Veg Soup": "",
//   "Manchow Soup": "",
//   "Clear Soup": "",
//   "Chicken Sweet Corn Soup": "",
//   "Chicken Hot & Sour Soup": "",
//   "Mutton Soup": "",
//   "Rasam": "",
//   "Green Salad": "",
//   "Cucumber Salad": "",
//   "Onion & Lemon Salad": "",
//   "Kachumber Salad": "",
//   "Russian Salad": "",
//   "Caesar Salad (Veg/Non-Veg)": "",
//   "Sprouts Salad": "",
//   "Paneer Butter Masala": "",
//   "Kadai Paneer": "",
//   "Shahi Paneer": "",
//   "Palak Paneer": "",
//   "Dal Makhani": "",
//   "Dal Tadka": "",
//   "Veg Kofta Curry": "",
//   "Chole Masala": "",
//   "Rajma Masala": "",
//   "Bhindi Masala": "",
//   "Baingan Bharta": "",
//   "Mix Veg Curry": "",
//   "Butter Chicken": "",
//   "Chicken Korma": "",
//   "Chicken Do Pyaza": "",
//   "Chicken Chettinad": "",
//   "Mutton Rogan Josh": "",
//   "Egg Curry": "",
//   "Fish Curry": "",
//   "Prawn Curry": "",
//   "Paneer Lababdar": "",
//   "Paneer Pasanda": "",
//   "Malai Kofta": "",
//   "Aloo Gobi": "",
//   "Mutter Paneer": "",
//   "Chicken Tikka Masala": "",
//   "Chicken Handi": "",
//   "Hyderabadi Mutton Curry": "",
//   "Goan Fish Curry": "",
//   "Prawn Masala Curry": "",
//   "Tandoori Roti": "",
//   "Butter Roti": "",
//   "Plain Naan (//Garlic)": "",
//   "Butter Naan": "",
//   "Garlic Naan": "",
//   "Lachha Paratha": "",
//   "Aloo Paratha": "",
//   "Paneer Paratha": "",
//   "Amritsari Kulcha": "",
//   "Roomali Roti": "",
//   "Poori": "",
//   "Chapati": "",
//   "Steamed Rice": "",
//   "Jeera Rice": "",
//   "Veg Pulao": "",
//   "Peas Pulao": "",
//   "Veg Biryani": "",
//   "Chicken Biryani": "",
//   "Mutton Biryani": "",
//   "Hyderabadi Dum Biryani": "",
//   "Egg Biryani": "",
//   "Fish Biryani": "",
//   "Curd Rice": "",
//   "Lemon Rice": "",
//   "Tamarind Rice": "",
//   "Veg Fried Rice": "",
//   "Chicken Fried Rice": "",
//   "Egg Fried Rice": "",
//   "Veg Hakka Noodles": "",
//   "Schezwan Veg Noodles": "",
//   "Chicken Hakka Noodles": "",
//   "Schezwan Chicken Noodles": "",
//   "Egg Noodles": "",
//   "Singapore Noodles": "",
//   "American Chopsuey": "",
//   "Paneer Tikka (BBQ style)": "",
//   "Soya Chaap Tikka": "",
//   "Tandoori Chicken": "",
//   "Chicken Seekh Kebab": "",
//   "Reshmi Kebab": "",
//   "Afghani Chicken": "",
//   "Mutton Seekh Kebab": "",
//   "Fish Tikka (Tandoor)": "",
//   "Prawns Tandoori": "",
//   "Margherita Pizza": "",
//   "Farmhouse Pizza": "",
//   "Paneer Tikka Pizza": "",
//   "Veggie Delight Pizza": "",
//   "Chicken Tikka Pizza": "",
//   "BBQ Chicken Pizza": "",
//   "Pepperoni Pizza": "",
//   "Veg Burger": "",
//   "Paneer Burger": "",
//   "Aloo Tikki Burger": "",
//   "Chicken Burger": "",
//   "Double Cheese Chicken Burger": "",
//   "Fish Burger": "",
//   "Fish Fry (Pomfret/Surmai)": "",
//   "Tandoori Fish": "",
//   "Fish Curry (Goan Style / Kerala Style)": "",
//   "Prawn Masala": "",
//   "Prawn Fry": "",
//   "Crab Curry": "",
//   "Lobster Masala": "",
//   "Gulab Jamun": "",
//   "Rasgulla": "",
//   "Rasmalai": "",
//   "Jalebi": "",
//   "Kheer": "",
//   "Phirni": "",
//   "Gajar Halwa": "",
//   "Moong Dal Halwa": "",
//   "Ice Cream Vanilla": "",
//   "Ice Cream Chocolate": "",
//   "Ice Cream Butterscotch": "",
//   "Kulfi Malai": "",
//   "Kulfi Pista": "",
//   "Kulfi Mango": "",
//   "Brownie with Ice Cream": "",
//   "Cheesecake": "",
//   "Pastries": "",
//   "Fresh Lime Soda (Sweet/Salt)": "",
//   "Cold Drink (Coke, Pepsi, etc.)": "",
//   "Orange Juices": "",
//   "Pineapple Juices": "",
//   "Watermelon Juices": "",
//   "Mosambi Juices": "",
//   "Lassi Sweet": "",
//   "Lassi Salted": "",
//   "Lassi Mango": "",
//   "Buttermilk Chaas": "",
//   "Jaljeera": "",
//   "Virgin Mojito": "",
//   "Blue Lagoon": "",
//   "Chocolate Milkshakes": "",
//   "Strawberry Milkshakes": "",
//   "Banana Milkshakes": "",
//   "Filter Coffee (South Indian Style)": "",
//   "Espresso": "",
//   "Cappuccino": "",
//   "Latte": "",
//   "Cold Coffee": "",
//   "Mocha": "",
//   "Tea": "",
//   "Papad Roasted": "",
//   "Papad Fried": "",
//   "Papad Masala": "",
//   "Pickles (Achar)": "",
//   "Boondi Raita": "",
//   "Onion Raita": "",
//   "Cucumber Raita": "",
//   "Pineapple Raita": "",
//   "French Fries": "",
//   "Masala Fries": "",
//   "Garlic Bread": "",
//   "Cheese Garlic Bread": "",
//   "Veg Thali": "",
//   "Special Thali": "",
//   "Non-Veg Thali": "",
//   "Idli": "",
//   "Plain Dosa": "",
//   "Masala Dosa": "",
//   "Rava Dosa": "",
//   "Mysore Dosa": "",
//   "Uttapam": "",
//   "Vada": "",
//   "Vada Pav": "",
//   "Pav Bhaji": "",
//   "Pani Puri": "",
//   "Bhel Puri": "",
//   "Sev Puri": "",
//   "Dahi Puri": "",
//   "Veg Sandwich": "",
//   "Club Sandwich": "",
//   "Grilled Sandwich": "",
//   "Chicken Sandwich": ""
// };










// const dishDict: Record<string, string> = {
//   "paneer pyaza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1753189879/Paneer-Do-Pyaza-2-3_konl7d.jpg",
//   "paneer makhni": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1753189817/paneer-butter-masala-recipe_yeumfs.webp",
//   "paneer-tikka": "",
//   "hara-bhara-kabab": "",
//   "veg-cutlet": "",
//   "spring-roll": "",
//   "stuffed-mushrooms": "",
//   "chicken-tikka": "",
//   "malai-tikka": "",
//   "fish-tikka": "",
//   "mutton-seekh-kebab": "",
//   "chilli-paneer-dry": "",
//   "chilli-chicken": "",
//   "gobi-manchurian": "",
//   "french-fries": "",
//   "nachos-with-cheese": "",
//   "tomato-soup": "",
//   "sweet-corn-soup": "",
//   "hot-sour-veg-soup": "",
//   "manchow-soup": "",
//   "clear-soup": "",
//   "chicken-sweet-corn-soup": "",
//   "chicken-hot-sour-soup": "",
//   "mutton-soup": "",
//   "rasam": "",
//   "green-salad": "",
//   "cucumber-salad": "",
//   "onion-lemon-salad": "",
//   "kachumber-salad": "",
//   "russian-salad": "",
//   "caesar-salad-veg-non-veg": "",
//   "sprouts-salad": "",
//   "paneer-butter-masala": "",
//   "kadai-paneer": "",
//   "shahi-paneer": "",
//   "palak-paneer": "",
//   "dal-makhani": "",
//   "dal-tadka": "",
//   "veg-kofta-curry": "",
//   "chole-masala": "",
//   "rajma-masala": "",
//   "bhindi-masala": "",
//   "baingan-bharta": "",
//   "mix-veg-curry": "",
//   "butter-chicken": "",
//   "chicken-korma": "",
//   "chicken-do-pyaza": "",
//   "chicken-chettinad": "",
//   "mutton-rogan-josh": "",
//   "egg-curry": "",
//   "fish-curry": "",
//   "prawn-curry": "",
//   "paneer-lababdar": "",
//   "paneer-pasanda": "",
//   "malai-kofta": "",
//   "aloo-gobi": "",
//   "mutter-paneer": "",
//   "chicken-tikka-masala": "",
//   "chicken-handi": "",
//   "hyderabadi-mutton-curry": "",
//   "goan-fish-curry": "",
//   "prawn-masala-curry": "",
//   "tandoori-roti": "",
//   "butter-roti": "",
//   "plain-naan-garlic": "",
//   "butter-naan": "",
//   "garlic-naan": "",
//   "lachha-paratha": "",
//   "aloo-paratha": "",
//   "paneer-paratha": "",
//   "amritsari-kulcha": "",
//   "roomali-roti": "",
//   "poori": "",
//   "chapati": "",
//   "steamed-rice": "",
//   "jeera-rice": "",
//   "veg-pulao": "",
//   "peas-pulao": "",
//   "veg-biryani": "",
//   "chicken-biryani": "",
//   "mutton-biryani": "",
//   "hyderabadi-dum-biryani": "",
//   "egg-biryani": "",
//   "fish-biryani": "",
//   "curd-rice": "",
//   "lemon-rice": "",
//   "tamarind-rice": "",
//   "veg-fried-rice": "",
//   "chicken-fried-rice": "",
//   "egg-fried-rice": "",
//   "veg-hakka-noodles": "",
//   "schezwan-veg-noodles": "",
//   "chicken-hakka-noodles": "",
//   "schezwan-chicken-noodles": "",
//   "egg-noodles": "",
//   "singapore-noodles": "",
//   "american-chopsuey": "",
//   "paneer-tikka-bbq-style": "",
//   "soya-chaap-tikka": "",
//   "tandoori-chicken": "",
//   "chicken-seekh-kebab": "",
//   "reshmi-kebab": "",
//   "afghani-chicken": "",
//   "fish-tikka-tandoor": "",
//   "prawns-tandoori": "",
//   "margherita-pizza": "",
//   "farmhouse-pizza": "",
//   "paneer-tikka-pizza": "",
//   "veggie-delight-pizza": "",
//   "chicken-tikka-pizza": "",
//   "bbq-chicken-pizza": "",
//   "pepperoni-pizza": "",
//   "veg-burger": "",
//   "paneer-burger": "",
//   "aloo-tikki-burger": "",
//   "chicken-burger": "",
//   "double-cheese-chicken-burger": "",
//   "fish-burger": "",
//   "fish-fry-pomfret-surmai": "",
//   "tandoori-fish": "",
//   "fish-curry-goan-kerala-style": "",
//   "prawn-masala": "",
//   "prawn-fry": "",
//   "crab-curry": "",
//   "lobster-masala": "",
//   "gulab-jamun": "",
//   "rasgulla": "",
//   "rasmalai": "",
//   "jalebi": "",
//   "kheer": "",
//   "phirni": "",
//   "gajar-halwa": "",
//   "moong-dal-halwa": "",
//   "ice-cream-vanilla": "",
//   "ice-cream-chocolate": "",
//   "ice-cream-butterscotch": "",
//   "kulfi-malai": "",
//   "kulfi-pista": "",
//   "kulfi-mango": "",
//   "brownie-with-ice-cream": "",
//   "cheesecake": "",
//   "pastries": "",
//   "fresh-lime-soda-sweet-salt": "",
//   "cold-drink-coke-pepsi": "",
//   "orange-juices": "",
//   "pineapple-juices": "",
//   "watermelon-juices": "",
//   "mosambi-juices": "",
//   "lassi-sweet": "",
//   "lassi-salted": "",
//   "lassi-mango": "",
//   "buttermilk-chaas": "",
//   "jaljeera": "",
//   "virgin-mojito": "",
//   "blue-lagoon": "",
//   "chocolate-milkshakes": "",
//   "strawberry-milkshakes": "",
//   "banana-milkshakes": "",
//   "filter-coffee-south-indian-style": "",
//   "espresso": "",
//   "cappuccino": "",
//   "latte": "",
//   "cold-coffee": "",
//   "mocha": "",
//   "tea": "",
//   "papad-roasted": "",
//   "papad-fried": "",
//   "papad-masala": "",
//   "pickles-achar": "",
//   "boondi-raita": "",
//   "onion-raita": "",
//   "cucumber-raita": "",
//   "pineapple-raita": "",
//   "french-fries-side": "",
//   "masala-fries": "",
//   "garlic-bread": "",
//   "cheese-garlic-bread": "",
//   "veg-thali": "",
//   "special-thali": "",
//   "non-veg-thali": "",
//   "idli": "",
//   "plain-dosa": "",
//   "masala-dosa": "",
//   "rava-dosa": "",
//   "mysore-dosa": "",
//   "uttapam": "",
//   "vada": "",
//   "vada-pav": "",
//   "pav-bhaji": "",
//   "pani-puri": "",
//   "bhel-puri": "",
//   "sev-puri": "",
//   "dahi-puri": "",
//   "veg-sandwich": "",
//   "club-sandwich": "",
//   "grilled-sandwich": "",
//   "chicken-sandwich": ""
// };















// {
//   "starters": [
//     "Paneer Tikka",
//     "Hara Bhara Kabab",
//     "Veg Cutlet",
//     "Spring Roll",
//     "Stuffed Mushrooms",
//     "Chicken Tikka",
//     "Malai Tikka",
//     "Fish Tikka",
//     "Mutton Seekh Kebab",
//     "Chilli Paneer Dry",
//     "Chilli Chicken",
//     "Gobi Manchurian",
//     "French Fries",
//     "Nachos with Cheese"
//   ],
//   "soup": [
//     "Tomato Soup",
//     "Sweet Corn Soup",
//     "Hot & Sour Veg Soup",
//     "Manchow Soup",
//     "Clear Soup",
//     "Chicken Sweet Corn Soup",
//     "Chicken Hot & Sour Soup",
//     "Mutton Soup",
//     "Rasam"
//   ],
//   "salad": [
//     "Green Salad",
//     "Cucumber Salad",
//     "Onion & Lemon Salad",
//     "Kachumber Salad",
//     "Russian Salad",
//     "Caesar Salad (Veg/Non-Veg)",
//     "Sprouts Salad"
//   ],
//   "mains": [
//     "Paneer Butter Masala",
//     "Kadai Paneer",
//     "Shahi Paneer",
//     "Palak Paneer",
//     "Dal Makhani",
//     "Dal Tadka",
//     "Veg Kofta Curry",
//     "Chole Masala",
//     "Rajma Masala",
//     "Bhindi Masala",
//     "Baingan Bharta",
//     "Mix Veg Curry",
//     "Butter Chicken",
//     "Chicken Korma",
//     "Chicken Do Pyaza",
//     "Chicken Chettinad",
//     "Mutton Rogan Josh",
//     "Egg Curry",
//     "Fish Curry",
//     "Prawn Curry"
//   ],
//   "curry": [
//     "Paneer Lababdar",
//     "Paneer Pasanda",
//     "Malai Kofta",
//     "Aloo Gobi",
//     "Mutter Paneer",
//     "Chicken Tikka Masala",
//     "Chicken Handi",
//     "Hyderabadi Mutton Curry",
//     "Goan Fish Curry",
//     "Prawn Masala Curry"
//   ],
//   "bread": [
//     "Tandoori Roti",
//     "Butter Roti",
//     "Plain Naan (//Garlic)",
//      "Butter Naan",
//      "Garlic Naan",
//     "Lachha Paratha",
//     "Aloo Paratha",
//     "Paneer Paratha",
//     "Amritsari Kulcha",
//     "Roomali Roti",
//     "Poori",
//     "Chapati"
//   ],
//   "rice": [
//     "Steamed Rice",
//     "Jeera Rice",
//     "Veg Pulao",
//     "Peas Pulao",
//     "Veg Biryani",
//     "Chicken Biryani",
//     "Mutton Biryani",
//     "Hyderabadi Dum Biryani",
//     "Egg Biryani",
//     "Fish Biryani",
//     "Curd Rice",
//     "Lemon Rice",
//     "Tamarind Rice",
//     "Veg Fried Rice",
//     "Chicken Fried Rice",
//     "Egg Fried Rice"
//   ],
//   "noodles": [
//     "Veg Hakka Noodles",
//     "Schezwan Veg Noodles",
//     "Chicken Hakka Noodles",
//     "Schezwan Chicken Noodles",
//     "Egg Noodles",
//     "Singapore Noodles",
//     "American Chopsuey"
//   ],
//   "bbq": [
//     "Paneer Tikka (BBQ style)",
//     "Soya Chaap Tikka",
//     "Tandoori Chicken",
//     "Chicken Seekh Kebab",
//     "Reshmi Kebab",
//     "Afghani Chicken",
//     "Mutton Seekh Kebab",
//     "Fish Tikka (Tandoor)",
//     "Prawns Tandoori"
//   ],
//   "pizza": [
//     "Margherita Pizza",
//     "Farmhouse Pizza",
//     "Paneer Tikka Pizza",
//     "Veggie Delight Pizza",
//     "Chicken Tikka Pizza",
//     "BBQ Chicken Pizza",
//     "Pepperoni Pizza"
//   ],
//   "burger": [
//     "Veg Burger",
//     "Paneer Burger",
//     "Aloo Tikki Burger",
//     "Chicken Burger",
//     "Double Cheese Chicken Burger",
//     "Fish Burger"
//   ],
//   "seafood": [
//     "Fish Fry (Pomfret/Surmai)",
//     "Tandoori Fish",
//     "Fish Curry (Goan Style / Kerala Style)",
//     "Prawn Masala",
//     "Prawn Fry",
//     "Crab Curry",
//     "Lobster Masala"
//   ],
//   "desserts": [
//     "Gulab Jamun",
//     "Rasgulla",
//     "Rasmalai",
//     "Jalebi",
//     "Kheer",
//     "Phirni",
//     "Gajar Halwa",
//     "Moong Dal Halwa",
//     "Ice Cream Vanilla",
//     "Ice Cream Chocolate",
//     "Ice Cream Butterscotch",
//     "Kulfi Malai",
//     "Kulfi Pista",
//     "Kulfi Mango",
//     "Brownie with Ice Cream",
//     "Cheesecake",
//     "Pastries"
//   ],
//   "drinks": [
//     "Fresh Lime Soda (Sweet/Salt)",
//     "Cold Drink (Coke, Pepsi, etc.)",
//     "Orange Juices",
//     "Pineapple Juices",
//     "Watermelon Juices",
//     "Mosambi Juices",
//     "Lassi Sweet",
//     "Lassi Salted",
//     "Lassi Mango",
//     "Buttermilk Chaas",
//     "Jaljeera",
//     "Virgin Mojito",
//     "Blue Lagoon",
//     "Chocolate Milkshakes",
//     "Strawberry Milkshakes",
//     "Banana Milkshakes"
//   ],
//   "coffee": [
//     "Filter Coffee (South Indian Style)",
//     "Espresso",
//     "Cappuccino",
//     "Latte",
//     "Cold Coffee",
//     "Mocha",
//     "Tea"
//   ],
//   "sides": [
//     "Papad Roasted",
//     "Papad Fried",
//     "Papad Masala",
//     "Pickles (Achar)",
//     "Boondi Raita",
//     "Onion Raita",
//     "Cucumber Raita",
//     "Pineapple Raita",
//     "French Fries",
//     "Masala Fries",
//     "Garlic Bread",
//     "Cheese Garlic Bread"
//   ],
//   "other": [
//     "Veg Thali",
//     "Special Thali",
//     "Non-Veg Thali",
//     "Idli",
//     "Plain Dosa",
//     "Masala Dosa",
//     "Rava Dosa",
//     "Mysore Dosa",
//     "Uttapam",
//     "Vada",
//     "Vada Pav",
//     "Pav Bhaji",
//     "Pani Puri",
//     "Bhel Puri",
//     "Sev Puri",
//     "Dahi Puri",
//     "Veg Sandwich",
//     "Club Sandwich",
//     "Grilled Sandwich",
//     "Chicken Sandwich"
//   ]
// }
