const dishDict: Record<string, string> ={
    "paneer tikka": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828551/Paneer_Tikka_lsuctd.png",
    "hara bhara kabab": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Hara_Bhara_Kabab_zvtnah.jpg",
    "veg cutlet": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756895191/Veg_Cutlet_smrrh9.jpg",
    "spring roll": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829584/Spring_Roll_gqjok6.webp",
    "stuffed mushrooms": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829584/Stuffed_Mushrooms_vhj58w.jpg",
    "chicken tikka": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828538/Chicken_Tikka_nychci.jpg",
    "chicken malai tikka": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828543/Malai_Chicken_Tikka_hiwzq7.jpg",
    "fish tikka": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828102/Fish_Tikka_e39csb.jpg",
    "mutton seekh kebab": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828290/Mutton_Seekh_Kebab_n9l7ue.jpg",
    "chilli paneer dry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Chilli_Paneer_Dry_zoydaa.jpg",
    "chilli chicken": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Chilli_Chicken_k8pf50.webp",
    "gobi manchurian": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828541/Gobi_Manchurian_zfqybh.jpg",
    "french fries": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828102/French_Fries_cy83gw.jpg",
    "nachos with cheese": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Nachos_with_Cheese_yzytru.jpg",
    "tomato soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756894416/Tomato_Soup_2_qpmjcp.jpg",
    "sweet corn soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756894743/Sweet_Corn_Soup_zx6wwe.jpg",
    "hot and sour veg soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Hot_Sour_Veg_Soup_njmrhu.jpg",
    "manchow soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828543/Manchow_Soup_rmd4nb.jpg",
    "clear soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Clear_Soup_rct2my.jpg",
    "chicken sweet corn soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828538/Chicken_Sweet_Corn_Soup_qib1kb.webp",
    "chicken hot and sour soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756895015/chicken_hot_and_sour_soup_lr3hjh.jpg",
    "mutton soup": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828544/Mutton_Soup_p5jk6v.jpg",
    "rasam": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828590/Rasam_blkykl.jpg",
    "green salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Green_Salad_y8pze8.jpg",
    "cucumber salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828540/Cucumber_Salad_nmgsgm.jpg",
    "onion salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Onion_Salad_mqkjn2.webp",
    "kachumber salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Kachumber_Salad_ysqsi3.jpg",
    "russian salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828614/Russian_Salad_okpxnh.png",
    "veg caesar salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828426/Caesar_Salad_Veg_uoqj3s.jpg",
    "chicken caesar salad":"https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828426/Caesar_Salad_Non_Veg_sviajn.avif",
    "sprouts salad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829584/Sprouts_Salad_rd4dti.jpg",
    "paneer butter masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828546/Paneer_Butter_Masala_lyas0d.jpg",
    "kadai paneer": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828543/Kadai_Paneer_irnwq4.jpg",
    "shahi paneer": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829532/Shahi_Paneer_o8psp9.jpg",
    "palak paneer": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Palak_Paneer_dt0qsp.webp",
    "dal makhani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828540/Dal_Makhani_ugjoi6.jpg",
    "dal tadka": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828540/Dal_Tadka_ufmzkq.webp",
    "chole masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Chole_Masala_vyunlx.webp",
    "rajma masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828564/Rajma_Masala_paikcm.jpg",
    "bhindi masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Bhindi_Masala_apxeac.jpg",
    "baingan bharta": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Baingan_Bharta_sudqic.webp",
    "mix veg curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828544/Mix_Veg_Curry_e7dyfw.jpg",
    "butter chicken": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828426/Butter_Chicken_pos8un.jpg",
    "chicken korma": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828538/Chicken_Korma_gbwgny.jpg",
    "chicken do pyaza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828390/Chicken_Do_Pyaza_rraqbu.jpg",
    "chicken chettinad": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828390/Chicken_Chettinad_vxc9bt.jpg",
    "egg curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Egg_Curry_cnpoes.png",
    "fish curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828394/Fish_Curry_zuxu8w.jpg",
    "prawn curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828423/Prawn_Curry_iogoxs.jpg",
    "paneer lababdar": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Paneer_Lababdar_bqaxtl.jpg",
    "paneer pasanda": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Paneer_Pasanda_sd4amg.jpg",
    "malai kofta": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828420/Malai_Kofta_debtot.jpg",
    "aloo gobi": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1757674935/Aloo_Gobi_alwo5x.webp",
    "mutter paneer": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Mutter_Paneer_ajnig3.jpg",
    "chicken tikka masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828392/Chicken_Tikka_Masala_ejjjln.jpg",
    "chicken handi": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828391/Chicken_Handi_ihkkxl.avif",
    "hyderabadi mutton curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Hyderabadi_Mutton_Curry_uabtq8.jpg",
    "goan fish curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828394/Goan_Fish_Curry_nhafoj.jpg",
    "prawn masala curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828423/Prawn_Masala_Curry_qi8ple.jpg",
    "tandoori roti": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Tandoori_Roti_eqte2d.jpg",
    "butter roti": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828389/Butter_Roti_qyu3vp.jpg",
    "plain naan": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Plain_Naan_t7qucg.jpg",
    "butter naan": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828389/Butter_Naan_yuevfu.jpg",
    "garlic naan": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828394/Garlic_Naan_wppoj0.jpg",
    "lachha paratha": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828420/Lachha_Paratha_kaqacg.jpg",
    "aloo paratha": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828354/Aloo_Paratha_eoyjcl.jpg",
    "paneer paratha": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Paneer_Paratha_idnabq.jpg",
    "amritsari kulcha": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828388/Amritsari_Kulcha_juqw85.avif",
    "roomali roti": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Roomali_Roti_u27lqd.webp",
    "poori": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Poori_aqx9vh.jpg",
    "chapati": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828389/Chapati_r5oplw.jpg",
    "steamed rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Steamed_Rice_pydmbz.jpg",
    "jeera rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828396/Jeera_Rice_iicnb6.jpg",
    "veg pulao": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Veg_Pulao_fyomio.jpg",
    "peas pulao": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Peas_Pulao_bbrhsx.jpg",
    "veg biryani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Veg_Biryani_jhlc6a.jpg",
    "chicken biryani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828390/Chicken_Biryani_hof67m.jpg",
    "mutton biryani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Mutton_Biryani_uxbiqm.jpg",
    "hyderabadi dum biryani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Hyderabadi_Dum_Biryani_pd1gdd.jpg",
    "egg biryani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828392/Egg_Biryani_owzooe.jpg",
    "fish biryani": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828393/Fish_Biryani_rzskte.jpg",
    "curd rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828392/Curd_Rice_jah2y7.jpg",
    "lemon rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828420/Lemon_Rice_t7zjmr.webp",
    "tamarind rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Tamarind_Rice_rsyk8p.jpg",
    "veg fried rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Veg_Fried_Rice_ldinhi.jpg",
    "chicken fried rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828391/Chicken_Fried_Rice_dxlpo9.jpg",
    "egg fried rice": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828393/Egg_Fried_Rice_xexio1.jpg",
    "veg hakka noodles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756894835/Veg_Hakka_Noodles_awqj4x.jpg",
    "schezwan veg noodles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828308/Schezwan_Veg_Noodles_zemgkl.jpg",
    "chicken hakka noodles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Chicken_Hakka_Noodles_xlpvdn.jpg",
    "schezwan chicken noodles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828307/Schezwan_Chicken_Noodles_xnmkqf.jpg",
    "egg noodles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Egg_Noodles_dfdf0s.jpg",
    "singapore noodles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828308/Singapore_Noodles_zfiiwq.jpg",
    "american chopsuey": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828095/American_Chopsuey_m6saio.jpg",
    "soya chaap tikka": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828320/Soya_Chaap_Tikka_mjhovm.jpg",
    "tandoori chicken": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828321/Tandoori_Chicken_py9oih.jpg",
    "chicken seekh kebab": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828094/Chicken_Seekh_Kebab_baiu3t.jpg",
    "reshmi kebab": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828307/Reshmi_Kebab_gepk2l.jpg",
    "afghani chicken": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828093/Afghani_Chicken_ao5yyp.jpg",
    "prawns tandoori": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Prawns_Tandoori_zqeibz.jpg",
    "margherita pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Margherita_Pizza_wdall4.jpg",
    "farmhouse pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Farmhouse_Pizza_bcpfyi.avif",
    "paneer tikka pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828292/Paneer_Tikka_Pizza_tiqu4l.jpg",
    "veggie delight pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828323/Veggie_Delight_Pizza_nmx5ej.jpg",
    "chicken tikka pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828095/Chicken_Tikka_Pizza_cnauox.jpg",
    "bbq chicken pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1757675604/BBQ_Chicken_Pizza_dfajrt.webp",
    "pepperoni pizza": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828294/Pepperoni_Pizza_mfqopx.jpg",
    "veg burger": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Veg_Burger_ia4gbb.jpg",
    "paneer burger": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828292/Paneer_Burger_hqwhnk.webp",
    "aloo tikki burger": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828094/Aloo_Tikki_Burger_yaz7fm.jpg",
    "chicken burger": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828099/Chicken_Burger_ahjw1l.jpg",
    "double cheese chicken burger": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Double_Cheese_Chicken_Burger_nwetbk.webp",
    "fish burger": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Fish_Burger_dtgbje.webp",
    "fish fry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Fish_Fry_c4na6k.jpg",
    "prawn fry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Prawn_Fry_hchyu1.jpg",
    "crab curry": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Crab_Curry_dfwuqi.jpg",
    "lobster masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828172/Lobster_Masala_btlg7p.jpg",
    "gulab jamun": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828104/Gulab_Jamun_nzxqlq.jpg",
    "rasgulla": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Rasgulla_nutbr9.jpg",
    "rasmalai": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828307/Rasmalai_gflyog.jpg",
    "jalebi": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Jalebi_adqinu.jpg",
    "kheer": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Kheer_pzp6m9.jpg",
    "phirni": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828295/Phirni_cm0aap.jpg",
    "gajar halwa": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828103/Gajar_Halwa_bho2ot.jpg",
    "moong dal halwa": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828290/Moong_Dal_Halwa_rqpvms.jpg",
    "ice cream vanilla": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828104/Ice_Cream_Vanilla_wupli8.jpg",
    "ice cream chocolate": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828104/Ice_Cream_Chocolate_hb9kyu.jpg",
    "ice cream butterscotch": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828104/Ice_Cream_Butterscotch_ok8oma.jpg",
    "kulfi malai": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Kulfi_Malai_wb4yrb.jpg",
    "kulfi pista": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828107/Kulfi_Pista_zvcrq3.png",
    "kulfi mango": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828106/Kulfi_Mango_chsnbx.webp",
    "brownie with ice cream": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Brownie_with_Ice_Cream_lnzymy.jpg",
    "cheesecake": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828099/Cheesecake_csdagr.jpg",
    "pastries": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828294/Pastries_gzmyhs.jpg",
    "fresh lime soda": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828102/Fresh_Lime_Soda_vhbsci.webp",
    "cold drink": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Cold_Drink_s94cuc.avif",
    "cold drink ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Cold_Drink_elgvke.jpg",
    "orange juices": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Orange_Juices_xvzo85.jpg",
    "pineapple juices": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828305/Pineapple_Juices_tp0oam.jpg",
    "watermelon juices": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828324/Watermelon_Juices_kj1viy.jpg",
    "mosambi juices": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828290/Mosambi_Juices_ixnkmf.jpg",
    "lassi sweet": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828141/Lassi_Sweet_dvurdc.jpg",
    "lassi salted": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828106/Lassi_Salted_vanroh.jpg",
    "lassi mango": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828106/Lassi_Mango_gsk80w.jpg",
    "lassi mango ":"https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Mango_Lassi_vqybw8.jpg",
    "buttermilk chaas": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Buttermilk_Chaas_i5zpjj.jpg",
    "jaljeera": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Jaljeera_lynxnn.jpg",
    "virgin mojito": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828323/Virgin_Mojito_rlhnnk.jpg",
    "blue lagoon": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Blue_Lagoon_mewum7.webp",
    "chocolate milkshakes": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/Chocolate_Milkshakes_yyu5di.avif",
    "strawberry milkshakes": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828320/Strawberry_Milkshakes_ndcfuh.jpg",
    "banana milkshakes": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828095/Banana_Milkshakes_hnr3wv.jpg",
    "filter coffee": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Filter_Coffee_qfeyz2.jpg",
    "espresso": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Espresso_kpbzfk.jpg",
    "cappuccino": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Cappuccino_lul1cm.jpg",
    "latte": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828151/Latte_whzzre.jpg",
    "cold coffee": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Cold_Coffee_abrh2p.jpg",
    "mocha": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Mocha_tmicct.jpg",
    "tea": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828321/tea_ifaujf.jpg",
    "tea ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828321/Tea_1_ekvti2.jpg",
    "papad roasted": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Papad_b8xds1.jpg",
    "papad fried": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Papad_Fried_hz2ayq.jpg",
    "papad masala": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Papad_Masala_picair.jpg",
    "pickles": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828304/Pickles_cnxtvu.jpg",
    "boondi raita": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828097/Boondi_Raita_x5kuii.webp",
    "onion raita": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Onion_Raita_tgahxd.jpg",
    "cucumber raita": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Cucumber_Raita_kbflns.webp",
    "pineapple raita": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828305/Pineapple_Raita_mlm0ck.jpg",
    "masala fries": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Masala_Fries_vtzvim.jpg",
    "garlic bread": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828103/Garlic_Bread_m0fhms.jpg",
    "cheese garlic bread": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828099/Cheese_Garlic_Bread_rm1tfr.jpg",
    "veg thali": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828323/Veg_Thali_jjgh5d.avif",
    "special thali": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828320/Special_Thali_zo2qpk.webp",
    "non veg thali": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Non_Veg_Thali_yt2po2.jpg",
    "idli": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828104/Idli_i4mfho.jpg",
    "plain dosa": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828305/Plain_Dosa_eanjsm.jpg",
    "masala dosa": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Masala_Dosa_efxkgo.jpg",
    "rava dosa": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828311/Rava_Dosa_r1ondt.png",
    "mysore dosa": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Mysore_Dosa_sspmh6.webp",
    "uttapam": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828321/Uttapam_fgpzpm.jpg",
    "vada": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Vada_opbzxf.jpg",
    "vada pav": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Vada_Pav_qhybm2.jpg",
    "pav bhaji": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Pav_Bhaji_aj2wy9.jpg",
    "pani puri": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Pani_Puri_wafcdg.jpg",
    "bhel puri": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/Bhel_Puri_lyyilm.jpg",
    "sev puri": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828308/Sev_Puri_y0u3lb.jpg",
    "dahi puri": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828099/Dahi_Puri_bldx14.webp",
    "veg sandwich": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Veg_Sandwich_spp57z.jpg",
    "club sandwich": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/Club_Sandwich_usbb5u.webp",
    "grilled sandwich": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828103/Grilled_Sandwich_lfpux7.jpg",
    "chicken sandwich": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828094/Chicken_Sandwich_fb2vms.jpg",
    "paneer tikka ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828292/Paneer_Tikka_2_o9niaj.jpg",
    "hara bhara kabab ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Hara_Bhara_Kabab_tksb4p.jpg",
    "veg cutlet ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756895191/Veg_Cutlet_2_t4esmb.webp",
    "spring roll ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829583/Spring_Roll_2_c1s4k1.jpg",
    "stuffed mushrooms ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829584/Stuffed_Mushrooms_2_izdvt5.jpg",
    "chicken tikka ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828538/Chicken_Tikka_2_zieaew.jpg",
    "chicken malai tikka ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Malai_Chicken_Tikka_2_ozokr8.jpg",
    "fish tikka ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828102/Fish_Tikka_2_t6wbtd.jpg",
    "mutton seekh kebab ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828290/Mutton_Seekh_Kebab_2_fegw5e.jpg",
    "chilli paneer dry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Chilli_Paneer_Dry_2_h0g0jc.jpg",
    "chilli chicken ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828538/Chilli_Chicken_2_yxkods.webp",
    "gobi manchurian ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828541/Gobi_Manchurian_2_qfgoyl.jpg",
    "french fries ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828541/French_Fries_wjb6j5.avif",
    "nachos with cheese ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Nachos_with_Cheese_2_dvou9q.jpg",
    "tomato soup ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756894416/Tomato_Soup_j9fem5.jpg",
    "sweet corn soup ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756894743/Sweet_Corn_Soup_2_aw6k5j.jpg",
    "hot and sour veg soup ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Hot_Sour_Veg_Soup_2_kshct0.jpg",
    "manchow soup ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828543/Manchow_Soup_2_zvy1is.jpg",
    "clear soup ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Clear_Soup_2_yxipq9.webp",
    "chicken hot and sour soup ":"https://res.cloudinary.com/dxnwguqtd/image/upload/v1756895051/chicken_hot_and_sour_soup_2_cks7uv.jpg",
    "mutton soup ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828544/Mutton_Soup_2_cldrns.jpg",
    "rasam ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828581/Rasam_2_b5tnbv.avif",
    "green salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828541/Green_Salad_2_zuvwar.jpg",
    "cucumber salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828540/Cucumber_Salad_2_ehkp4c.webp",
    "onion salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Onion_Salad_2_gyczft.webp",
    "kachumber salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828542/Kachumber_Salad_2_dm8pqs.jpg",
    "russian salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828601/Russian_Salad_2_fqahao.jpg",
    "veg caesar salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828426/Caesar_Salad_Veg_2_jyafsj.jpg",
    "chicken caesar salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828426/Caesar_Salad_Non_Veg_2_lycxks.jpg",
    "sprouts salad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756829584/Sprouts_Salad_2_o18syj.jpg",
    "paneer butter masala ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828546/Paneer_Butter_Masala_2_gv3m0t.jpg",
    "kadai paneer ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828543/Kadai_Paneer_2_emib1b.jpg",
    "shahi paneer ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828933/Shahi_Paneer_2_l8jw3q.jpg",
    "palak paneer ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828545/Palak_Paneer_2_hllizp.jpg",
    "dal makhani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828540/Dal_Makhani_2_rzvbbv.webp",
    "dal tadka ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828540/Dal_Tadka_2_eignqn.jpg",
    "chole masala ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828539/Chole_Masala_2_jgkzzu.jpg",
    "rajma masala ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828546/Rajma_Masala_2_dhksdy.jpg",
    "baingan bharta ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Baingan_Bharta_2_j44bzk.jpg",
    "mix veg curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828544/Mix_Veg_Curry_2_tnuvz9.avif",
    "butter chicken ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Butter_Chicken_2_sialia.jpg",
    "chicken korma ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828391/Chicken_Korma_2_ymtf0m.webp",
    "chicken do pyaza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828390/Chicken_Do_Pyaza_2_pf2ec1.jpg",
    "chicken chettinad ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828390/Chicken_Chettinad_2_cr6apt.jpg",
    "egg curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Egg_Curry_2_nwy2ec.png",
    "fish curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828393/Fish_Curry_2_eoj9le.jpg",
    "prawn curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828423/Prawn_Curry_2_lldpcd.jpg",
    "paneer lababdar ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Paneer_Lababdar_2_jsugzo.jpg",
    "paneer pasanda ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Paneer_Pasanda_2_xqqtaa.jpg",
    "malai kofta ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828420/Malai_Kofta_2_irbox5.jpg",
    "aloo gobi ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1757674911/Aloo_Gobi_2_jqflqh.jpg",
    "mutter paneer ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828420/Mutter_Paneer_2_rx04fu.jpg",
    "chicken tikka masala ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828392/Chicken_Tikka_Masala_2_oihqtx.jpg",
    "chicken handi ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828391/Chicken_Handi_2_q241vb.jpg",
    "hyderabadi mutton curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Hyderabadi_Mutton_Curry_2_fiuh4g.jpg",
    "goan fish curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828394/Goan_Fish_Curry_2_tlkqps.jpg",
    "prawn masala curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828423/Prawn_Masala_Curry_2_s3byz1.jpg",
    "tandoori roti ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Tandoori_Roti_2_pqcbzl.jpg",
    "butter roti ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828389/Butter_Roti_2_kgxhr7.jpg",
    "plain naan ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Plain_Naan_2_ffh0ya.jpg",
    "butter naan ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828389/Butter_Naan_2_ptw1ue.jpg",
    "garlic naan ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828394/Garlic_Naan_2_kzawxx.jpg",
    "lachha paratha ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828396/Lachha_Paratha_2_wddjql.jpg",
    "aloo paratha ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828324/Aloo_Paratha_2_uss89a.jpg",
    "paneer paratha ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Paneer_Paratha_2_tvt3jw.webp",
    "amritsari kulcha ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828371/Amritsari_Kulcha_2_tdles0.avif",
    "roomali roti ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828423/Roomali_Roti_2_ienjzw.avif",
    "poori ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Poori_2_i8v36l.jpg",
    "chapati ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828389/Chapati_2_inaye5.jpg",
    "steamed rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Steamed_Rice_2_yr64us.jpg",
    "jeera rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Jeera_Rice_2_m3jnpx.jpg",
    "veg pulao ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828425/Veg_Pulao_2_dihspq.jpg",
    "peas pulao ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828422/Peas_Pulao_2_lqrpy3.jpg",
    "veg biryani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Veg_Biryani_2_hdrbdh.jpg",
    "chicken biryani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828390/Chicken_Biryani_2_mxqpc7.jpg",
    "mutton biryani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828421/Mutton_Biryani_2_ozuktk.jpg",
    "hyderabadi dum biryani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828395/Hyderabadi_Dum_Biryani_2_z8oa0s.avif",
    "egg biryani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828392/Egg_Biryani_2_dunrd7.jpg",
    "fish biryani ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828393/Fish_Biryani_2_dirvkm.jpg",
    "curd rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828392/Curd_Rice_2_aypc6f.jpg",
    "lemon rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828420/Lemon_Rice_2_sgkkqd.jpg",
    "veg fried rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828424/Veg_Fried_Rice_2_pohrjd.jpg",
    "chicken fried rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828391/Chicken_Fried_Rice_2_qknulu.jpg",
    "egg fried rice ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828393/Egg_Fried_Rice_2_hyhywj.jpg",
    "veg hakka noodles ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756894835/Veg_Hakka_Noodles_2_jejvo1.jpg",
    "schezwan veg noodles ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828308/Schezwan_Veg_Noodles_2_tfc1jn.jpg",
    "chicken hakka noodles ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Chicken_Hakka_Noodles_2_dtlboc.jpg",
    "schezwan chicken noodles ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828307/Schezwan_Chicken_Noodles_2_ztwsm6.jpg",
    "egg noodles ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Egg_Noodles_2_rzekea.jpg",
    "american chopsuey ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828094/American_Chopsuey_2_yslhj5.jpg",
    "soya chaap tikka ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828319/Soya_Chaap_Tikka_2_enmypm.jpg",
    "tandoori chicken ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828321/Tandoori_Chicken_2_fhwwxn.jpg",
    "chicken seekh kebab ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828095/Chicken_Seekh_Kebab_2_udkvky.jpg",
    "reshmi kebab ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828307/Reshmi_Kebab_2_nju9po.jpg",
    "afghani chicken ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828093/Afghani_Chicken_2_dqflst.jpg",
    "prawns tandoori ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Prawns_Tandoori_2_zpp5sa.jpg",
    "margherita pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Margherita_Pizza_2_m8rjme.jpg",
    "farmhouse pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Farmhouse_Pizza_2_qweajf.webp",
    "paneer tikka pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828292/Paneer_Tikka_Pizza_2_o8jppv.jpg",
    "veggie delight pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828323/Veggie_Delight_Pizza_2_dy75di.jpg",
    "chicken tikka pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828095/Chicken_Tikka_Pizza_2_koqtcv.jpg",
    "bbq chicken pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/BBQ_Chicken_Pizza_2_kh8l4n.jpg",
    "pepperoni pizza ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828294/Pepperoni_Pizza_2_b69qr4.jpg",
    "veg burger ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Veg_Burger_2_sgwfmr.jpg",
    "paneer burger ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828292/Paneer_Burger_2_scabey.webp",
    "aloo tikki burger ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828094/Aloo_Tikki_Burger_2_pjtrjy.jpg",
    "chicken burger ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828100/Chicken_Burger_2_agbjjt.jpg",
    "fish fry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Fish_Fry_2_zcxehe.jpg",
    "prawn fry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Prawn_Fry_2_letqwj.jpg",
    "crab curry ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Crab_Curry_2_qsi7fd.jpg",
    "lobster masala ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828161/Lobster_Masala_2_hj23mv.jpg",
    "gulab jamun ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828103/Gulab_Jamun_2_yxjwuo.jpg",
    "rasgulla ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Rasgulla_2_c2wd5p.jpg",
    "rasmalai ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828306/Rasmalai_2_qlmu1o.jpg",
    "jalebi ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Jalebi_2_xcvavl.jpg",
    "kheer ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Kheer_2_mcacxi.jpg",
    "phirni ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828294/Phirni_2_v7ylhz.jpg",
    "gajar halwa ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828102/Gajar_Halwa_2_zoz05j.jpg",
    "moong dal halwa ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828290/Moong_Dal_Halwa_2_dwqh04.jpg",
    "cheesecake ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828099/Cheesecake_2_gsmx3u.jpg",
    "pastries ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Pastries_2_tc6dmt.jpg",
    "fresh lime soda ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828102/Fresh_Lime_Soda_2_gdx3if.jpg",
    "orange juices ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Orange_Juices_2_aaysi4.jpg",
    "pineapple juices ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828305/Pineapple_Juices_2_vfgcm1.jpg",
    "watermelon juices ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828323/Watermelon_Juices_2_fymozo.jpg",
    "mosambi juices ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828290/Mosambi_Juices_2_okftms.jpg",
    "lassi sweet ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828132/Lassi_Sweet_2_jwaepq.jpg",
    "virgin mojito ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828323/Virgin_Mojito_2_rdwzut.jpg",
    "blue lagoon ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Blue_Lagoon_2_ofijfu.jpg",
    "chocolate milkshakes ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828095/Chocolate_Milkshakes_2_b1esmm.webp",
    "strawberry milkshakes ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828320/Strawberry_Milkshakes_2_r2tj1p.jpg",
    "banana milkshakes ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/Banana_Milkshakes_2_wpcqq7.jpg",
    "filter coffee ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Filter_Coffee_2_nvcf9q.jpg",
    "cappuccino ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Cappuccino_2_mi8zfu.jpg",
    "pickles ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828295/Pickles_2_ifmwyz.jpg",
    "garlic bread ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828103/Garlic_Bread_2_j2bi6g.jpg",
    "veg thali ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Veg_Thali_2_xwowcf.jpg",
    "special thali ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828320/Special_Thali_2_stvs9q.webp",
    "non veg thali ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Non_Veg_Thali_2_ckvjts.jpg",
    "idli ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828104/Idli_2_nmcl86.jpg",
    "plain dosa ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828305/Plain_Dosa_2_hfl6h2.jpg",
    "masala dosa ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828289/Masala_Dosa_2_dta7pa.jpg",
    "rava dosa ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828307/Rava_Dosa_2_fspmqz.webp",
    "mysore dosa ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828291/Mysore_Dosa_2_sxiyh1.webp",
    "uttapam ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828321/Uttapam_2_dljxhr.jpg",
    "vada ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Vada_2_sc1h50.jpg",
    "vada pav ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Vada_Pav_2_mmaxrg.jpg",
    "pav bhaji ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828294/Pav_Bhaji_2_j9cufn.jpg",
    "pani puri ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828293/Pani_Puri_2_vp9syi.jpg",
    "bhel puri ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/Bhel_Puri_2_fauypp.jpg",
    "sev puri ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828308/Sev_Puri_2_ph0jjz.webp",
    "dahi puri ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828098/Dahi_Puri_2_n4wp2o.webp",
    "veg sandwich ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828322/Veg_Sandwich_2_pcdfui.jpg",
    "club sandwich ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828096/Club_Sandwich_2_dzchwn.jpg",
    "grilled sandwich ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828105/Grilled_Sandwich_2_p03gqe.png",
    "chicken sandwich ": "https://res.cloudinary.com/dxnwguqtd/image/upload/v1756828101/Chicken_Sandwich_2_mtvpol.jpg"
};

// menuList contains the list of dish names available in the menu.
// Each item in menuList should have a corresponding image URL in dishDict.
// Exported for use in other modules that need the menu list.
export const menuList = ['paneer tikka',
 'hara bhara kabab',
 'veg cutlet',
 'spring roll',
 'stuffed mushrooms',
 'chicken tikka',
 'chicken malai tikka',
 'fish tikka',
 'mutton seekh kebab',
 'chilli paneer dry',
 'chilli chicken',
 'gobi manchurian',
 'french fries',
 'nachos with cheese',
 'tomato soup',
 'sweet corn soup',
 'hot and sour veg soup',
 'manchow soup',
 'clear soup',
 'chicken sweet corn soup',
 'chicken hot and sour soup',
 'mutton soup',
 'rasam',
 'green salad',
 'cucumber salad',
 'onion salad',
 'kachumber salad',
 'russian salad',
 'veg caesar salad',
 'sprouts salad',
 'paneer butter masala',
 'kadai paneer',
 'shahi paneer',
 'palak paneer',
 'dal makhani',
 'dal tadka',
 'chole masala',
 'rajma masala',
 'bhindi masala',
 'baingan bharta',
 'mix veg curry',
 'butter chicken',
 'chicken korma',
 'chicken do pyaza',
 'chicken chettinad',
 'egg curry',
 'fish curry',
 'prawn curry',
 'paneer lababdar',
 'paneer pasanda',
 'malai kofta',
 'aloo gobi',
 'mutter paneer',
 'chicken tikka masala',
 'chicken handi',
 'hyderabadi mutton curry',
 'goan fish curry',
 'prawn masala curry',
 'tandoori roti',
 'butter roti',
 'plain naan',
 'butter naan',
 'garlic naan',
 'lachha paratha',
 'aloo paratha',
 'paneer paratha',
 'amritsari kulcha',
 'roomali roti',
 'poori',
 'chapati',
 'steamed rice',
 'jeera rice',
 'veg pulao',
 'peas pulao',
 'veg biryani',
 'chicken biryani',
 'mutton biryani',
 'hyderabadi dum biryani',
 'egg biryani',
 'fish biryani',
 'curd rice',
 'lemon rice',
 'tamarind rice',
 'veg fried rice',
 'chicken fried rice',
 'egg fried rice',
 'veg hakka noodles',
 'schezwan veg noodles',
 'chicken hakka noodles',
 'schezwan chicken noodles',
 'egg noodles',
 'singapore noodles',
 'american chopsuey',
 'soya chaap tikka',
 'tandoori chicken',
 'chicken seekh kebab',
 'reshmi kebab',
 'afghani chicken',
 'prawns tandoori',
 'margherita pizza',
 'farmhouse pizza',
 'paneer tikka pizza',
 'veggie delight pizza',
 'chicken tikka pizza',
 'bbq chicken pizza',
 'pepperoni pizza',
 'veg burger',
 'paneer burger',
 'aloo tikki burger',
 'chicken burger',
 'double cheese chicken burger',
 'fish burger',
 'fish fry',
 'prawn fry',
 'crab curry',
 'lobster masala',
 'gulab jamun',
 'rasgulla',
 'rasmalai',
 'jalebi',
 'kheer',
 'phirni',
 'gajar halwa',
 'moong dal halwa',
 'ice cream vanilla',
 'ice cream chocolate',
 'ice cream butterscotch',
 'kulfi malai',
 'kulfi pista',
 'kulfi mango',
 'brownie with ice cream',
 'cheesecake',
 'pastries',
 'fresh lime soda',
 'cold drink',
 'orange juices',
 'pineapple juices',
 'watermelon juices',
 'mosambi juices',
 'lassi sweet',
 'lassi salted',
 'lassi mango',
 'buttermilk chaas',
 'jaljeera',
 'virgin mojito',
 'blue lagoon',
 'chocolate milkshakes',
 'strawberry milkshakes',
 'banana milkshakes',
 'filter coffee',
 'espresso',
 'cappuccino',
 'latte',
 'cold coffee',
 'mocha',
 'tea',
 'papad roasted',
 'papad fried',
 'papad masala',
 'pickles',
 'boondi raita',
 'onion raita',
 'cucumber raita',
 'pineapple raita',
 'masala fries',
 'garlic bread',
 'cheese garlic bread',
 'veg thali',
 'special thali',
 'non veg thali',
 'idli',
 'plain dosa',
 'masala dosa',
 'rava dosa',
 'mysore dosa',
 'uttapam',
 'vada',
 'vada pav',
 'pav bhaji',
 'pani puri',
 'bhel puri',
 'sev puri',
 'dahi puri',
 'veg sandwich',
 'club sandwich',
 'grilled sandwich',
 'chicken sandwich']

export default dishDict;



